### ISSUE TITLE
update and orUpdate cause an errror inside MongoDB when the set cause includes an _id property

### ISSUE THREAD

**Issue by mattwagl** [thenativeweb/wolkenkit#159] opened 2019-06-26 15:22 UTC
### What is this bug about?

When using the `update` or the `add({}).orUpdate({})` functions inside a readModel projection, it is possible to provide an `_id` field inside the update statement. This will cause a MongoError inside the readModel since `_id` field is immutable and should not be changed. After this the readModel crashes and even `wolkenkit reload` cannot get the readModel into a clean state.

### What steps are needed to reproduce the bug?

- Create a sample application using the chat template
- Update the messages list using the follwing projection:

```javascript
  'communication.message.liked' (messages, event) {
    messages.update({
      where: { id: event.aggregate.id },
      set: {
        _id: event.aggregate.id,
        likes: event.data.likes
      }
    });
  }
```

- Start the application
- Call `wolkenkit logs --follow`
- Create a new message and like it

### What is the expected result?

- The function should ignore the `_id` field

### What is the actual result?

- The readModel crashes
- `wolkenkit logs` reports the following error

```json
{"host":"wolkenkit-broker","pid":7,"id":1,"timestamp":1561561965161,"level":"fatal","message":"An unexpected error occured.","application":{"name":"wolkenkit-broker","version":"3.1.0"},"module":{"name":"wolkenkit-broker","version":"3.1.0"},"source":"/wolkenkit/app.js","metadata":{"err":{"name":"MongoError","message":"After applying the update to the document {_id: ObjectId('5d1388e5af904f0006e0b777') , ...}, the (immutable) field '_id' was found to have been altered to _id: \"a956ee5c-69cb-4619-860a-d084573894e0\"","stack":"MongoError: After applying the update to the document {_id: ObjectId('5d1388e5af904f0006e0b777') , ...}, the (immutable) field '_id' was found to have been altered to _id: \"a956ee5c-69cb-4619-860a-d084573894e0\"\n    at Function.create (/wolkenkit/node_modules/mongodb-core/lib/error.js:43:12)\n    at toError (/wolkenkit/node_modules/mongodb/lib/utils.js:149:22)\n    at coll.s.topology.update (/wolkenkit/node_modules/mongodb/lib/operations/collection_ops.js:1370:39)\n    at /wolkenkit/node_modules/mongodb-core/lib/connection/pool.js:532:18\n    at process._tickCallback (internal/process/next_tick.js:61:11)"}}}
```

**Comment by goloroden** [comment] 2019-06-27 07:45
@mattwagl This may sound like a stupid question, but why do you try to update the `_id` field at all?

**Comment by mattwagl** [comment] 2019-06-27 13:00
:-) Good question. It came up in an application where there actually was an `_id` field inside the data. So of course this shouldn't be the norm but I still asked myself if this should crash the whole application. Because as a developer you're not aware of the fact that you're not allowed to set this specific field. Another solution would be to add a hint to the docs?

**Comment by goloroden** [comment] 2019-06-27 13:03
The problem is (as usual 😉) a little bit larger than one might expect at first sight: The fact that `_id` is a reserved name is due to the fact that we use MongoDB as the foundation of the read model right now. If we used another database system (and we might do so in the future), other field names could be invalid. So whether it's `_id` or something else, is implementation-specific in the end.

Hence it is not *that* easy to come up with a generic solution, because simply disallowing `_id` won't be enough or flexible enough.

To cut a long story short, for now I think I'd vote for actually going the way you suggested with updating the documentation. Would you mind coming up with a PR for that?

**Comment by mattwagl** [comment] 2019-06-27 15:46
:-) I'm wondering where to do that? Does it still make sense to do this in the `old` documnetation repo? Or  would it make sense to update it inside the new monorepo-branch? Then I would simply add it to the latest version.

**Comment by goloroden** [comment] 2019-06-28 08:18
Actually, I don't know if we will need it in the next version anymore, since the read model gets a redesign from scratch anyway. Maybe just leave this issue open for now, and then let's have another look when we get closer to the release of 4.0.

**Comment by goloroden** [comment] 2019-10-24 20:57
As you can see in [this example projection](https://github.com/thenativeweb/wolkenkit/blob/e1cf6501c14481018f4474cc60a43c6c12746632/__temp__/sampleApplicationWithTypeScript/server/views/games/projections/PlayingGameOpened.ts#L5-L14), with the new v4 read model wolkenkit won't provide an abstraction layer over the read model database any more, but instead you will be using the database's npm module.

This allows to use the full potential of the database, and it makes it lots easier to support a variety of databases. But OTOH this also means that it's up to you to use the database reasonably and avoid errors.

I think that the pros outweigh the cons here, but unfortunately that's the price to pay in this case. Of course a crashing projection should not bring wolkenkit down completely, so this will be fixed, but apart from that I fear it's up to you in v4 to avoid this issue.

**Closed by goloroden** 2019-10-24 20:57 UTC
Labels: Bug, Read model
