### ISSUE TITLE
Arrays in an aggregate's state can not be replaced with an empty one

### ISSUE THREAD

**Issue by zibur** [thenativeweb/wolkenkit#93] opened 2018-11-12 20:41 UTC
### What is this bug about?

When an aggregate's state contains an array with content and you want to replace it with an empty one, it stays filled.

### What steps are needed to reproduce the bug?

- Start https://github.com/thenativeweb/wolkenkit-boards
- Attach the debugger to the `writeModel`
- Mount a new board
- Clean up the board
- Rename board

### What is the expected result?

With the attached debugger I expect the `postIds` array of the state to be empty.

### What is the actual result?

The `postIds` array of the state is still filled with the `postId` of the initial post.

**Comment by goloroden** [comment] 2018-11-13 04:43
I have been able to reproduce the bug, and so I can confirm it. I reproduced it in a slightly different way, with less components involved, but the result is basically the same.

### What steps are needed to reproduce the bug?

- Start [wolkenkit-boards](https://github.com/thenativeweb/wolkenkit-boards), both server and client
- Mount a new board
- Clean up the board (this works)
- Clean up the board again

### Expected result

The first call to *clean up* should result in an [empty `postIds` array](https://github.com/thenativeweb/wolkenkit-boards/blob/18f0d490f69be2e95c8c3f89b03634600204eeb3/server/writeModel/collaboration/board.js#L183-L187), which should then [cause a `Board already empty` error](https://github.com/thenativeweb/wolkenkit-boards/blob/18f0d490f69be2e95c8c3f89b03634600204eeb3/server/writeModel/collaboration/board.js#L126-L132) in the second try, which in turn should be shown in the UI.

### Actual result

The error doesn't happen, which means that the `postIds` array has not been emptied – which in turn means the same as what was originally reported by @zibur.

### Reason

I have tried to track down the cause of this issue, and the reason is in the implementation of [the `setState` function](https://github.com/thenativeweb/wolkenkit-core/blob/4634dd0eeb1513208db5160c26b867ea3aca18b9/repository/Aggregate.js#L96-L98). It does `merge` the current with the new state, which doesn't work if an array contains less elements than before (because then you merge the old values in). This means that we need to figure out how to improve this. How can we merge correctly?

**Comment by goloroden** [comment] 2018-11-13 17:34
@zibur This has been fixed and will be part of the upcoming wolkenkit 3.0 release 😊

**Closed** 2018-11-13 17:33 UTC
Labels: Bug, Write model
