### ISSUE TITLE
Wolkenkit application crashes with 'Error [ERR_STREAM_WRITE_AFTER_END]'

### ISSUE THREAD

**Issue by timrach** [thenativeweb/wolkenkit#161] opened 2019-07-08 14:58 UTC
### What is this bug about?
At some (seemingly random) point in time my wolkenkit application crashes with 'Error [ERR_STREAM_WRITE_AFTER_END]'. 
The client application shows '502 Bad Gateway'.

### What steps are needed to reproduce the bug?

The application connected to the wolkenkit application is working an automated routine:
1. Take an image with a webcam
2. Upload the image via DepotClient
3. Add the filename to an container aggregate

The upload step is executed every ~5 seconds.
This procedure can lead to up to 1200 filenames in a single container aggregate.  
The image file size is not greater than 250kb.

I will write a minimal working example trying to reproduce the error.

### What is the expected result?
Wolkenkit should be running stable without crashes.

### What is the actual result?
At some point the hosted wolkenkit application crashes unexpectedly. 
The most recent crash occured after 4 days uptime (according to `docker ps`).

In my client application I get following error: 
```
.../node_modules/wolkenkit-client/dist/apiBuilder/aggregates/readModel/ListAggregate.js:126
      throw err;
      ^
[UnexpectedStatusCode: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
] {
  name: 'UnexpectedStatusCode',
  code: 'EUNEXPECTEDSTATUSCODE',
  message: '<html>\r\n' +
    '<head><title>502 Bad Gateway</title></head>\r\n' +
    '<body bgcolor="white">\r\n' +
    '<center><h1>502 Bad Gateway</h1></center>\r\n' +
    '<hr><center>nginx/1.14.2</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  cause: undefined,
  statusCode: 502
}
```

Wolkenkit logs shows following entry: 

```
Application failed unexpectedly. (fatal)
wolkenkit-broker::wolkenkit-broker@3.1.0::tailwind@4.0.0 (/wolkenkit/node_modules/tailwind/dist/TailwindApp.js)
14:23:46.446@2019-07-08 6#11177
{
  err: {
    name: 'Error [ERR_STREAM_WRITE_AFTER_END]',
    message: 'write after end',
    stack: 'Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ServerResponse.write (_http_outgoing.js:567:10)
    at Client.send (/wolkenkit/node_modules/json-lines/dist/route/Client.js:40:18)
    at Timer.sendHeartbeat (/wolkenkit/node_modules/json-lines/dist/route/index.js:25:16)
    at Timer.emit (events.js:187:15)
    at /wolkenkit/node_modules/timer2/dist/Timer.js:58:16
    at process._tickCallback (internal/process/next_tick.js:61:11)'
  }
}
```

### What else should we know?
The container aggregates get relatively large (JSON Object with ~8000 lines at ~250kb for a full container with 1200 filenames).  
Could this be a problem?

**Comment by goloroden** [comment] 2019-07-08 16:00
> The container aggregates get relatively large (JSON Object with ~8000 lines at ~250kb for a full container with 1200 filenames).

This should not be a problem, at least right now I can't imagine what may cause problems here. Also, aggregates are not limited in size, so I don't think that this should be the cause for this.

I actually also doubt that is has anything to do with uploading the images to the depot, since the error seems to happen in the broker.

> I will write a minimal working example trying to reproduce the error.

This would be really great, as otherwise it's hard to reproduce (and analyze and fix) it.

**Comment by timrach** [comment] 2019-08-26 12:33
So...I could not reproduce the error reliably with a minimal working example. BUT I made the observation that the error does not occur when the device running the application is connected to the internet via ethernet cable instead of a WiFi connection. I know nothing about network communication but maybe someone else sees a connection between the error and wifi  🤷‍♂

**Comment by goloroden** [comment] 2020-02-20 18:01
Since 4.0 will be a complete rewrite from scratch we will probably not fix this any more for v3. We need to wait and see whether 4.0 has similar problems, but if so they should be way easier to track down due to the structure of 4.0. Hence closing this as won‘t fix.

**Closed by goloroden** 2020-02-20 18:01 UTC
Labels: Bug, Various
