### ISSUE TITLE
Incorrect table name for snapshots is defined in domain events store options schema

### ISSUE THREAD

**Issue by yktv4** [thenativeweb/wolkenkit#1255] opened 2020-08-18 15:58 UTC
### What is this bug about?

You can't run the app with Docker because validation of env variables fails.

### What is the expected result?

I expect to be able to execute `docker-compose -f deployment/docker-compose/single-process.postgres.yml up` without any errors.

### What is the actual result?
I get the following error:
```
{
  "id": 0,
  "hostname": "fe8b33ebc45d",
  "processId": 7,
  "application": {
    "name": "wolkenkit-bank",
    "version": "0.0.1"
  },
  "module": {
    "name": "wolkenkit",
    "version": "4.0.0-internal.65"
  },
  "source": "/app/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/app.js",
  "timestamp": 1597760159584,
  "level": "fatal",
  "message": "An unexpected error occured.",
  "metadata": {
    "ex": {
      "origins": [
        {
          "code": "VALIDATION_OBJECT_REQUIRED",
          "message": "Missing required property: type",
          "path": "$.type"
        }
      ],
      "name": "Error",
      "message": "Missing required property: type (at consumerProgressStoreOptions.type).",
      "stack": "Error: Missing required property: type (at consumerProgressStoreOptions.type).\n    at Value.validate (/app/node_modules/validate-value/build/lib/Value.js:23:23)\n    at Object.fromEnvironmentVariables (/app/node_modules/wolkenkit/build/lib/runtimes/shared/fromEnvironmentVariables.js:12:19)\n    at /app/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/app.js:33:58\n    at Object.<anonymous> (/app/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/app.js:154:3)\n    at Module._compile (internal/modules/cjs/loader.js:1256:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)\n    at Module.load (internal/modules/cjs/loader.js:1105:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:967:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n    at internal/main/run_main_module.js:17:47"
    }
  }
}
```

### What steps are needed to reproduce the bug?

- create sample chat app
- run `docker-compose -f deployment/docker-compose/single-process.postgres.yml up`
- observe the docker-compose output

### What else should we know?

I was using ctp-4.0.0-internal.65 to reproduce this

**Comment by goloroden** [comment] 2020-08-18 17:33
This seems to be a duplicate of #1212 (which has just been fixed by #1213).

We'll need to figure out whether this is still relevant, and either merge or close it.

**Comment by goloroden** [comment] 2020-08-18 17:37
@yktv4 Can you please verify whether the problem still persists in `4.0.0-internal.75`?

If so, this issues along with #1256 can be closed.
If not, could you please drop us a quick note?

**Comment by goloroden** [comment] 2020-08-20 15:22
Not relevant any more, hence closed.

**Closed by goloroden** 2020-08-20 15:22 UTC
Labels: Bug
