### ISSUE TITLE
When trying to execute "wolkenkit init" I get the error "Template not found"

### ISSUE THREAD

**Issue by MuwuM** [thenativeweb/wolkenkit#1] opened 2017-06-20 20:35 UTC
Following the Tutorial in documentation [initializing-the-application](https://docs.wolkenkit.io/1.0.0/guides/creating-your-first-application/creating-the-application/#initializing-the-application) I get the error "Template not found" when executing "wolkenkit init".

Console:
```
wolkenkitdev@wolkenkitdev ~/jsdoc $ cd chat/
wolkenkitdev@wolkenkitdev ~/jsdoc/chat $ ls -l
total 0
wolkenkitdev@wolkenkitdev ~/jsdoc/chat $ wolkenkit init
✗ Failed to initialize a new application.
  Template not found.
```

This is running with a linux mint installation within a VirtualBox VM on Windows Host. Network is configured as NAT. browsing the web (and installation) worked without setting proxy configuration (so I did not touch them).

**Comment by goloroden** [comment] 2017-06-20 20:36
Is `git` installed?

**Comment by MuwuM** [comment] 2017-06-20 20:43
No, it wasn't.

installed it:
then I got:
```
wolkenkitdev@wolkenkitdev ~/jsdoc/chat $ wolkenkit init
⠸The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
⠴se you sure you want to continue connecting (yes/no)? 
✗ Failed to initialize a new application.
  Template not found.

```
I tried to type yes when the question was shown, but I am not sure whether it was executed successful.

each following `wolkenkit init` shows:
```
wolkenkitdev@wolkenkitdev ~/jsdoc/chat $ wolkenkit init
✗ Failed to initialize a new application.
  Template not found.
```

**Comment by goloroden** [comment] 2017-06-20 20:45
Okay, I think the problem is that the CLI expects you to be signed in to GitHub - which I guess you aren't in the VM. So, for now, as a workaround, I'd suggest to add your VM's SSH key to GitHub, so you can access GitHub in an authenticated way.

What we are going to do is fix the CLI with respect to two things:

- You should get a better error message if `git` is not installed.
- You should not be required to be authenticated against GitHub.

I'll let you know once an updated CLI is available.

**Comment by goloroden** [comment] 2017-06-20 20:48
(Does this fix it for you?)

**Comment by goloroden** [comment] 2017-06-20 20:52
PS: Alternatively, could you please try

```
$ wolkenkit init --template https://github.com/thenativeweb/wolkenkit-template-chat.git
```

*without* being authenticated, and see whether this works?

**Comment by MuwuM** [comment] 2017-06-20 20:59
adding authentication worked.

Removed certificate again and second work-arround also worked

**Comment by goloroden** [comment] 2017-06-20 20:59
Thanks a lot 😊 

Then we are going to fix this, and release an update of the CLI soon. As said, we will inform you using this issue once it's done.

**Comment by goloroden** [comment] 2017-06-20 21:41
Will both be fixed in upcoming `1.0.1`.

**Comment by goloroden** [comment] 2017-06-20 22:41
If you want to, run:

```
$ wolkenkit update
$ wolkenkit --version
```

This should return `1.0.1`. Then, both problems should be gone. If you want to do us a favor - could you please double-check this?

**Comment by goloroden** [comment] 2017-06-20 22:53
`1.0.1` has been released 😊 

Thanks for your great help today, and for evaluating wolkenkit 😊 
If we can help in any other way, feel free to contact us!

**Closed by goloroden** 2017-06-20 22:53 UTC
Labels: Bug, In progress

**Comment by MuwuM** [comment] 2017-06-21 06:52
Retested with version `1.0.1`. 
Both issues seems to be fixed.
